export const kenyanCounties = [
    "Baringo", "Bomet", "Bungoma", "Busia", "Elgeyo Marakwet", "Embu", "Garissa", "Homa Bay", "Isiolo", "Kajiado",
    "Kakamega", "Kericho", "Kiambu", "Kilifi", "Kirinyaga", "Kisii", "Kisumu", "Kitui", "Kwale", "Laikipia",
    "Lamu", "Machakos", "Makueni", "Mandera", "Marsabit", "Meru", "Migori", "Mombasa", "Murang'a", "Nairobi",
    "Nakuru", "Nandi", "Narok", "Nyamira", "Nyandarua", "Nyeri", "Samburu", "Siaya", "Taita Taveta", "Tana River",
    "Tharaka Nithi", "Trans Nzoia", "Turkana", "Uasin Gishu", "Vihiga", "Wajir", "West Pokot"
];

export const countyTowns = {
    "Elgeyo Marakwet": ["Iten", "Kapsowar", "Chebiemit", "Flax"],
    "Nairobi": ["Nairobi Central", "Westlands", "Dagoretti", "Karen", "Embakasi", "Kasarani", "Kibera"],
    "Mombasa": ["Mombasa Island", "Nyali", "Changamwe", "Kisauni", "Likoni", "Jomvu"],
    "Nakuru": ["Nakuru City", "Naivasha", "Gilgil", "Molo", "Njoro", "Rongai"],
    "Kiambu": ["Kiambu Town", "Thika", "Ruiru", "Kikuyu", "Limuru", "Karuri"],
    "Uasin Gishu": ["Eldoret", "Burnt Forest", "Turbo", "Ziwa"],
    "Kisumu": ["Kisumu City", "Ahero", "Muhoroni", "Maseno"],
    "Machakos": ["Machakos Town", "Athi River", "Kangundo", "Matuu"],
    "Kajiado": ["Kajiado Town", "Ngong", "Kitengela", "Namanga", "Loitokitok"],
    "Kilifi": ["Kilifi Town", "Malindi", "Mtwapa", "Mariakani", "Watamu"],
    "Bungoma": ["Bungoma Town", "Webuye", "Kimilili", "Chwele"],
    "Kakamega": ["Kakamega Town", "Mumias", "Butere", "Lumakanda"],
    "Kericho": ["Kericho Town", "Litein", "Kipkelion"],
    "Nandi": ["Kapsabet", "Nandi Hills"],
    "Laikipia": ["Nanyuki", "Nyahururu", "Rumuruti"],
    "Meru": ["Meru Town", "Maua", "Nkubu"],
    "Nyeri": ["Nyeri Town", "Karatina", "Othaya", "Chaka"],
    "Murang'a": ["Murang'a Town", "Kenol", "Kangema"],
    "Homa Bay": ["Homa Bay Town", "Mbita", "Oyugis"],
    "Migori": ["Migori Town", "Isebania", "Rongo", "Kehancha"],
    "Kisii": ["Kisii Town", "Ogembo", "Keroka"],
    "Trans Nzoia": ["Kitale", "Endebess"],
    "Narok": ["Narok Town", "Kilgoris"],
    "Bomet": ["Bomet Town", "Sotik"],
    "Baringo": ["Kabarnet", "Eldama Ravine", "Marigat"],
    "West Pokot": ["Kapenguria", "Makutano"],
    "Turkana": ["Lodwar", "Kakuma", "Lokichogio"],
    "Samburu": ["Maralal", "Baragoi"],
    "Marsabit": ["Marsabit Town", "Moyale", "Laisamis"],
    "Isiolo": ["Isiolo Town", "Garba Tulla"],
    "Mandera": ["Mandera Town", "El Wak"],
    "Wajir": ["Wajir Town", "Habaswein"],
    "Garissa": ["Garissa Town", "Dadaab"],
    "Tana River": ["Hola", "Garsen", "Bura"],
    "Lamu": ["Lamu Town", "Mpeketoni"],
    "Taita Taveta": ["Voi", "Wundanyi", "Mwatate", "Taveta"],
    "Embu": ["Embu Town", "Siakago", "Manyatta"],
    "Kirinyaga": ["Kerugoya", "Kutus", "Wanguru", "Sagana"],
    "Nyandarua": ["Ol Kalou", "Njabini", "Engineer"],
    "Kitui": ["Kitui Town", "Mwingi", "Mutomo"],
    "Makueni": ["Wote", "Mtito Andei", "Kibwezi"],
    "Tharaka Nithi": ["Chuka", "Chogoria", "Marimanti"],
    "Vihiga": ["Mbale", "Chavakali", "Luanda"],
    "Busia": ["Busia Town", "Malaba", "Nambale"],
    "Siaya": ["Siaya Town", "Bondo", "Ugunja"],
    "Nyamira": ["Nyamira Town", "Keroka"]
};
